### ISSUE TITLE
Jumble options when presenting

### ISSUE THREAD

**Issue by vamsidharmuthireddy** [Pi-Rasp/Cog-Sci-WebApp#2]
If all the safe and risky options keep appearing at the same locations, users might get hint that the experiment is favouring specific option. So jumble them. 

1. Give id's to both options(Eg: left, right) and then have two groups Group1=[left,right], Group2=[right,left]
2. Random Prob>0.5 select Group2, otherwise select Group1
3. This group will tell us where the safe and risky options and feedback should be placed
4. Group1, safe to the left and risky to the right opposite to the Group2

**Comment by nitinnilesh** [comment]
Generating a random number(0, 1) and shuffling the options based on that. Each and every time the options will be jumbled.
